Algoritmo "Troca de Pneu"
// > SINALIZAR A VIA
// > VERIFICAR A SITUAÇÃO DO ESTEPE
// > VERIFICAR SE POSSUI CHAVE DE RODA
// > VERIFICAR SE POSSUI MACACO
// > FOLGAR OS PARAFUSOS
// > LEVANTAR O CARRO
// > RETIRAR O PENEU FURADO
// > COLOCAR O ESTEPE
// > APERTAR OS PARAFUSOS
// > ABAIXAR O MACACO
// > APERTAR OS PARAFUSOS NOVAMENTE
// > FIM
Var
// Seção de Declarações das variáveis 


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 


Fimalgoritmo